datasource:
  db:
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${DATABASE_URL}

ebean:
  migration:
    run: true
